### PR TITLE
Python 3.9

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
@jjhelmus Thanks for the setuptools update, this passed locally for me now :)

**Review by jakirkham — APPROVED** [review]

**Comment by jjhelmus** [comment]
`cross-python_osx-arm64` is needed for Python 3.9

**Comment by isuruf** [comment]
Needs to backport https://github.com/benfogle/crossenv/pull/37 to https://github.com/conda-forge/crossenv-feedstock

**Comment by mariusvniekerk** [comment]
Closed by #66

**Pull request closed without merging**
