### PR TITLE
Add Python 3.8 prerelease builds

### PR DESCRIPTION
**Pull request by jjhelmus**
Add configuration files for a Python 3.8 build using the packages in the conda-forge/label/pre-3.8 channel.
These files were added manually and will not survive a rerender.

### CODE REVIEW

**Comment by ocefpaf** [comment]
> These files were added manually and will not survive a rerender.

I guess that is fine b/c we will probably need only a single release of this, right?

**Comment by jjhelmus** [comment]
> I guess that is fine b/c we will probably need only a single release of this, right?

Yes, one release should be sufficient to allow folks to test out 3.8 during the alpha, beta, rc period.  I wasn't planning on building many 3.8 packages, just a few key ones; pip, pytest, nose, and maybe cython along with their dependencies.

**Comment by jjhelmus** [comment]
Forgot to add AppVeyor builds, give me a minute to update the file.

**Comment by jjhelmus** [comment]
Let's see how this work!

**Pull request merged**
